version: '3'
services:
  redis-cluster:
    image: grokzen/redis-cluster:5.0.12
    # must override the hardcoded ip in the container
    environment:
      IP: "0.0.0.0"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
      - "7006:7006"
      - "7007:7007"