spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        es:
          url: jdbc:es://localhost:9200
          mapperLocations: classpath:mapper/*.xml
    driver-class-name: org.elasticsearch.xpack.sql.jdbc.EsDriver
    type: org.springframework.jdbc.datasource.DriverManagerDataSource