spring:
  datasource:
    url: jdbc:es://127.0.0.1:9200?user=elastic&password=elastic
    #ConnectionTestQuery: SELECT 1
    driverClassName: org.elasticsearch.xpack.sql.jdbc.EsDriver
    type: com.alibaba.druid.pool.DruidDataSource
    username: elastic
    password: elastic
    mapperLocations: classpath*:esMapper/*.xml


  mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml
    global-config:
      refresh: true
      db-config:
        db-type: mysql
        id-type: uuid
        logic-delete-value: 1
        logic-not-delete-value: 0
        table-prefix: hydra_
        table-underline: true
    configuration:
      map-underscore-to-camel-case: true
      aggressive-lazy-loading: true
      auto-mapping-behavior: partial
      auto-mapping-unknown-column-behavior: none
      cache-enabled: true
      call-setters-on-nulls: false
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          defaultBrokerPort: 9092
          required-acks: 1
      bindings:
        share_order_log_input:
          destination: student_topic  # 订阅的topic
          contentType: application/json
          group: student_group
          consumer:
            partitioned: true                 # 开启分区
            instance-count: 2                 # 分区数量
            instance-index: 0                 # 当前实例的下标，这里指定了一个，多实例启动时指定另一个
            concurrency: 2
        share_order_log_output:
          destination: student_topic  # 订阅的topic
          content-type: application/json            # 消息的格式